/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AaTuhl0PJ1B
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import { Input } from "@/components/ui/input"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function searchproduct() {
  const products = [
    {
      id: 1,
      name: "Acme Wireless Headphones",
      description: "High-quality audio with noise cancellation",
      price: 99.99,
      image: "/placeholder.svg",
      category: "Electronics",
      color: "black",
    },
    {
      id: 2,
      name: "Cozy Cotton Throw Blanket",
      description: "Soft and warm for all seasons",
      price: 39.99,
      image: "/placeholder.svg",
      category: "Home",
      color: "gray",
    },
    {
      id: 3,
      name: "Outdoor Adventure Backpack",
      description: "Durable and spacious for hiking",
      price: 79.99,
      image: "/placeholder.svg",
      category: "Outdoors",
      color: "green",
    },
    {
      id: 4,
      name: "Ergonomic Office Chair",
      description: "Supportive and adjustable for all-day comfort",
      price: 199.99,
      image: "/placeholder.svg",
      category: "Furniture",
      color: "black",
    },
    {
      id: 5,
      name: "Organic Cotton T-Shirt",
      description: "Soft and sustainable fashion",
      price: 24.99,
      image: "/placeholder.svg",
      category: "Clothing",
      color: "white",
    },
    {
      id: 6,
      name: "Smart Home Hub",
      description: "Control your home with voice commands",
      price: 79.99,
      image: "/placeholder.svg",
      category: "Electronics",
      color: "white",
    },
  ]
  const [selectedCategories, setSelectedCategories] = useState([])
  const [selectedColors, setSelectedColors] = useState([])
  const handleCategoryChange = (category) => {
    if (selectedCategories.includes(category)) {
      setSelectedCategories(selectedCategories.filter((c) => c !== category))
    } else {
      setSelectedCategories([...selectedCategories, category])
    }
  }
  const handleColorChange = (color) => {
    if (selectedColors.includes(color)) {
      setSelectedColors(selectedColors.filter((c) => c !== color))
    } else {
      setSelectedColors([...selectedColors, color])
    }
  }
  const filteredProducts = useMemo(() => {
    return products.filter((product) => {
      if (selectedCategories.length > 0 && !selectedCategories.includes(product.category)) {
        return false
      }
      if (selectedColors.length > 0 && !selectedColors.includes(product.color)) {
        return false
      }
      return true
    })
  }, [selectedCategories, selectedColors])
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-white shadow-md p-4 flex items-center">
        <div className="flex-1 relative">
          <Input
            type="search"
            placeholder="Search products..."
            className="w-full bg-gray-100 rounded-md pl-10 pr-4 py-2"
          />
          <div className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
        </div>
      </header>
      <div className="flex flex-1">
        <div className="bg-gray-100 p-6 border-r border-gray-200 w-64 overflow-auto md:w-auto md:border-r-0 md:p-0 md:bg-transparent">
          <Collapsible className="md:hidden">
            <CollapsibleTrigger className="text-lg font-medium mb-4 flex items-center justify-between">
              Filters
              <ChevronDownIcon className="w-5 h-5 transition-transform data-[state=open]:rotate-180" />
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-6">
              <div>
                <h2 className="text-lg font-medium mb-4">Categories</h2>
                <div className="grid grid-cols-1 gap-2">
                  {["Electronics", "Home", "Outdoors", "Furniture", "Clothing"].map((category) => (
                    <Label key={category} className="flex items-center gap-2">
                      <Checkbox
                        checked={selectedCategories.includes(category)}
                        onCheckedChange={() => handleCategoryChange(category)}
                      />
                      {category}
                    </Label>
                  ))}
                </div>
              </div>
              <div>
                <h2 className="text-lg font-medium mb-4">Colors</h2>
                <div className="grid grid-cols-3 gap-2">
                  {["black", "gray", "green", "white"].map((color) => (
                    <Label key={color} className="flex items-center gap-2">
                      <Checkbox
                        checked={selectedColors.includes(color)}
                        onCheckedChange={() => handleColorChange(color)}
                      />
                      <div className={`w-4 h-4 rounded-full bg-${color}-500`} />
                    </Label>
                  ))}
                </div>
              </div>
            </CollapsibleContent>
          </Collapsible>
          <div className="hidden md:block">
            <h2 className="text-lg font-medium mb-4">Categories</h2>
            <div className="grid grid-cols-1 gap-2">
              {["Electronics", "Home", "Outdoors", "Furniture", "Clothing"].map((category) => (
                <Label key={category} className="flex items-center gap-2">
                  <Checkbox
                    checked={selectedCategories.includes(category)}
                    onCheckedChange={() => handleCategoryChange(category)}
                  />
                  {category}
                </Label>
              ))}
            </div>
            <h2 className="text-lg font-medium mt-6 mb-4">Colors</h2>
            <div className="grid grid-cols-3 gap-2">
              {["black", "gray", "green", "white"].map((color) => (
                <Label key={color} className="flex items-center gap-2">
                  <Checkbox checked={selectedColors.includes(color)} onCheckedChange={() => handleColorChange(color)} />
                  <div className={`w-4 h-4 rounded-full bg-${color}-500`} />
                </Label>
              ))}
            </div>
          </div>
        </div>
        <div className="flex-1 p-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {filteredProducts.map((product) => (
            <div key={product.id} className="bg-white rounded-lg shadow-md overflow-hidden">
              <img
                src="/placeholder.svg"
                alt={product.name}
                width={300}
                height={200}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "300/200", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium">{product.name}</h3>
                <p className="text-gray-500 text-sm">{product.description}</p>
                <div className="flex items-center justify-between mt-4">
                  <span className="text-lg font-medium">${product.price}</span>
                  <Button size="sm">Add to Cart</Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
